### PR TITLE
update default values with new syntax

### PR DESCRIPTION
**Pull request by TPei**
I got some errors when trying to use this shard, default value and type declaration order syntax seems to have changed

### CODE REVIEW

**Comment by TPei** [comment]
getting some type inference errors though...

**Comment by veelenga** [comment]
Nice try 😸 . Do you want to try to fix it completely or should i merge it and fix on master branch ?

**Comment by TPei** [comment]
I'm struggling a bit with broad Proc return type definitions, seeing as `(-> Object)` is not allowed...
`instance variable '@enter' of AASM::State must be (( -> Nil) | ( -> Void) | Nil), not ( -> Int32)`
So if you want to take over, go ahead 😃

**Comment by veelenga** [comment]
Ok, this one looks good. Thanks...

**Pull request merged**
